server:
  port: ${SERVER_PORT:8080}

sentry:
  dsn: https://b7b02a49b4031327059e36430753f700@o4510496632930304.ingest.us.sentry.io/4510496642695168
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  exception-resolver-order: -2147483647
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
    minimum-level: info
  logs:
    enabled: true

spring:
  threads:
    virtual:
      enabled: false
  application:
    name: mohago-nocar
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mohago_nocar}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6378

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

odsay:
  request-url: https://api.odsay.com/v1/api/searchPubTransPathT
  key: ${ODSAY_API_KEY}
  execution-interval-mills: 230

redis:
  streams:
    odsay:
      main: odsay-transit-api-requests
      dlq: odsay-api-failures
    plan:
      main: plan-events
      dlq: plan-events-failures
    course:
      optimized:
        main: optimized-course
        dlq: travel-spot-optimized-failures #삭제

google:
  maps:
    distance : https://maps.googleapis.com/maps/api/distancematrix/json
  api-key : ${GOOGLE_API_KEY}
  firebase:
    key:
      path: ${FIREBASE_KEY_PATH}

kakao:
  local:
    category: https://dapi.kakao.com/v2/local/search/category
  api-key: ${KAKAO_API_KEY}

discord:
  webhook-url: sdfdsfdsf

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    root: info
#    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG
#    com.zaxxer.hikari: DEBUG
#    org.springframework.data.redis.stream: TRACE
#    org.springframework.data.redis: TRACE
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    com.fasterxml.jackson.databind: DEBUG
#    org.springframework.http.converter.json: trace
#    io.sentry: trace

#logging:
#  level:
#    root: info
#    com:
#      google:
#        firebase: debug
#
#    io.lettuce.core.protocol: TRACE
#    io.lettuce.core.RedisClient: TRACE
#    org.springframework.data.redis: trace
#    io:
#      lettuce: trace

#    root: debug
#    jdk.virtualThread: debug

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:~/mohagoNoCar
#    username: sa
#    password:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/mohagoNoCarTest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6378